/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-123511-g3e8bec7871-20260316"
#endif /* AVUTIL_FFVERSION_H */
